version: '3'

services:
  app:
    build:
      context: ./node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 60s docker-entrypoint.sh 
    command: ["node", "index"]
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    ports:
      - 3000:3000
    depends_on:
      - db
  
  nginx:
    restart: always
    build:
        context: ./nginx
    container_name: nginx_app
    ports:
        - "80:80"
    networks:
      - node-network


  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodebd
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
